name: flight_pipeline
version: '1.0'
config-version: 2

profile: databricks

models:
  flight_pipeline:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table

