version: 2

sources:
  - name: airline_source
    database: dbt_akerqeli        # your catalog
    schema: dbt_akerqeli          # same as catalog if schema matches
    tables:
      - name: bronzer                # Bronze table

  - name: health_source
    database: dbt_akerqeli
    schema: dbt_akerqeli
    tables:
      - name: silvergold             # Silver/Gold table

